# Generated by Django 4.1.7 on 2023-03-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Description')),
                ('language_add', models.CharField(max_length=100)),
                ('date_loaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
