# Generated by Django 4.1.7 on 2023-03-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img_loaded',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
